config/routes.rb
Rails.application.routes.draw do
  resources :xetra_instruments
  resources :nasdaq_instruments

  root 'home#index'
  post 'nasdaq_instruments/read_csv' => 'nasdaq_instruments#read_csv'
  post 'xetra_instruments/readCsv' => 'xetra_instruments#readCsv'
  post '/' => 'home#scrape'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/finance_object.rb
class FinanceObject < ApplicationRecord
  belongs_to :owner_isntrument, polymorphic: true
end

app/models/google_finance_object.rb
class GoogleFinanceObject < ApplicationRecord
  belongs_to :owner_isntrument, polymorphic: true
end

app/models/nasdaq_instrument.rb
class NasdaqInstrument < ApplicationRecord
  has_one :finance_object, as: :owner_instrument, dependent: :destroy
  validates :name, :presence => true
  validates :symbol, :presence => true, :uniqueness => true
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates :symbol, :presence => true, :uniqueness => true
end

app/models/xetra_instrument.rb
class XetraInstrument < ApplicationRecord
  has_one :finance_object, as: :owner_instrument, dependent: :destroy
  validates :name, :presence => true
  validates :symbol, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require "google_finance_scraper"
require "yahoo_finance_scraper"

class HomeController < ApplicationController
  before_action :set_exchanges, only: [:index, :scrape]
  def index
  end

  def scrape
    @google_stock = GoogleFinanceScraper.fetch(params[:exchange], params[:search])
    @yahoo_stock = YahooFinanceScraper.fetch(params[:search])

    render :index
  end

  private
  def set_exchanges
    @exchanges = {"NASDAQ"=>"NASDAQ", "XETRA"=>"ETR"}
  end
end

app/controllers/nasdaq_instruments_controller.rb
require "alpha_vantage_api"
require "csv_reader"
require "yahoo_finance_scraper"

class NasdaqInstrumentsController < ApplicationController
  before_action :set_nasdaq_instrument, only: [:edit, :update, :destroy]
  before_action :set_and_update_nasdaq_instrument, only: [:show]
  before_action :set_nasdaq_instruments, only: [:index]

  # GET /nasdaq_instruments
  # GET /nasdaq_instruments.json
  def index
  end

  # GET /nasdaq_instruments/1
  # GET /nasdaq_instruments/1.json
  def show
    @weeks = AlphaVantageApi.fetch_weekly(@nasdaq_instrument.symbol)
    @threemonths = AlphaVantageApi.three_month_weekly(@nasdaq_instrument.symbol)
    @threemonthpr = AlphaVantageApi.three_month_dev_pr(@nasdaq_instrument.symbol)
  end

  # GET /nasdaq_instruments/new
  def new
    @nasdaq_instrument = NasdaqInstrument.new
  end

  # GET /nasdaq_instruments/1/edit
  def edit
  end

  # POST /nasdaq_instruments
  # POST /nasdaq_instruments.json
  def create
    @nasdaq_instrument = NasdaqInstrument.new(nasdaq_instrument_params)
    @nasdaq_instrument.finance_object = FinanceObject.create!

    respond_to do |format|
      if @nasdaq_instrument.save
        format.html { redirect_to @nasdaq_instrument, notice: "nasdaq_instrument was successfully created." }
        format.json { render :show, status: :created, location: @nasdaq_instrument }
      else
        format.html { render :new }
        format.json { render json: @nasdaq_instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nasdaq_instruments/1
  # PATCH/PUT /nasdaq_instruments/1.json
  def update
    respond_to do |format|
      if @nasdaq_instrument.update(nasdaq_instrument_params)
        format.html { redirect_to @nasdaq_instrument, notice: "nasdaq_instrument was successfully updated." }
        format.json { render :show, status: :ok, location: @nasdaq_instrument }
      else
        format.html { render :edit }
        format.json { render json: @nasdaq_instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nasdaq_instruments/1
  # DELETE /nasdaq_instruments/1.json
  def destroy
    @nasdaq_instrument.destroy
    respond_to do |format|
      format.html { redirect_to nasdaq_instruments_url, notice: "nasdaq_instrument was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def read_csv
    if !Delayed::Job.any?{|job| job.handler.include? 'CsvReader'}
      CsvReader.delay.read_nasdaq_instruments
    end
    redirect_to nasdaq_instruments_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_nasdaq_instruments
    @nasdaq_instruments = NasdaqInstrument.
        where("name like ?", "%#{params[:search]}%").
        paginate(:page => params[:page], :per_page => 50).
        order("name")
  end

  def set_nasdaq_instrument
    @nasdaq_instrument = NasdaqInstrument.find(params[:id])
  end

  def set_and_update_nasdaq_instrument
    @nasdaq_instrument = NasdaqInstrument.find(params[:id])
    @fo = YahooFinanceScraper.update_instrument(@nasdaq_instrument.symbol)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def nasdaq_instrument_params
    params.require(:nasdaq_instrument).permit(:name, :symbol)
  end
end

app/controllers/xetra_instruments_controller.rb
require "csv_reader"

class XetraInstrumentsController < ApplicationController
  before_action :set_xetra_instrument, only: [:show, :edit, :update, :destroy]
  before_action :set_instruments, only: [:index]

  # GET /xetra_instruments
  # GET /xetra_instruments.json
  def index
  end

  # GET /xetra_instruments/1
  # GET /xetra_instruments/1.json
  def show
    @fo = @xetra_instrument.finance_object
  end

  # GET /xetra_instruments/new
  def new
    @xetra_instrument = XetraInstrument.new
  end

  # GET /xetra_instruments/1/edit
  def edit
  end

  # POST /xetra_instruments
  # POST /xetra_instruments.json
  def create
    @xetra_instrument = XetraInstrument.new(xetra_instrument_params)
    @xetra_instrument.finance_object = FinanceObject.create!

    respond_to do |format|
      if @xetra_instrument.save
        format.html { redirect_to @xetra_instrument, notice: "Xetra instrument was successfully created." }
        format.json { render :show, status: :created, location: @xetra_instrument }
      else
        format.html { render :new }
        format.json { render json: @xetra_instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /xetra_instruments/1
  # PATCH/PUT /xetra_instruments/1.json
  def update
    respond_to do |format|
      if @xetra_instrument.update(xetra_instrument_params)
        format.html { redirect_to @xetra_instrument, notice: "Xetra instrument was successfully updated." }
        format.json { render :show, status: :ok, location: @xetra_instrument }
      else
        format.html { render :edit }
        format.json { render json: @xetra_instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xetra_instruments/1
  # DELETE /xetra_instruments/1.json
  def destroy
    @xetra_instrument.destroy
    respond_to do |format|
      format.html { redirect_to xetra_instruments_url, notice: "Xetra instrument was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def readCsv
    CsvReader.read_xetra_instruments
    redirect_to xetra_instruments_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instruments
      @xetra_instruments = XetraInstrument.
          where("name like ?", "%#{params[:search]}%").
          paginate(:page => params[:page], :per_page => 50).
          order("name")
    end

    def set_xetra_instrument
      @xetra_instrument = XetraInstrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def xetra_instrument_params
      params.require(:xetra_instrument).permit(:name, :symbol, :isin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nasdaq_instruments_helper.rb
module NasdaqInstrumentsHelper
end

app/helpers/xetra_instruments_helper.rb
module XetraInstrumentsHelper
end

app/views/home/index.html.erb
<h1>Stocksniffer v1.0</h1>

<h4>Test Google Finance scraper: </h4>

<div>
  <%= form_tag root_path do %>
      <p>
        Symbol: <%= text_field_tag "search", "AAPL" %>
        <%= select_tag("exchange", options_from_collection_for_select(@exchanges, :last, :first)) %>
        <%= submit_tag "Search", class:"btn-xs btn-primary"%>
      </p>
  <% end %>
</div>

<div>
  Google scraper (deprecated): <%= @google_stock %>
</div>
<br>
<div>
  Yahoo scraper: <%= @yahoo_stock %>
</div>

<div>
  <br>
  Apple Inc - AAPL<br>
  Facebook Inc. - FB<br>
  Microsoft Corporation - MSFT<br>
  Tesla Inc. - TSLA<br>
  ... <br>
  (https://www.google.com/finance?q=#{exchange}%3A#{symbol})<br>
  (https://finance.yahoo.com/quote/#{symbol}?p=#{symbol})<br>
  <i>Latest fetch as HTML at Rails.root("tmp/latest_search.html")</i>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == "notice" ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render "layouts/navigation_links" %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to "NASDAQ", nasdaq_instruments_path %></li>
<li><%= link_to "XETRA", xetra_instruments_path %></li>
<li><%= link_to "Coverage Report", "coverage/index.html" %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Stocksniffer" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Stocksniffer" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => "reload" %>
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render "layouts/navigation" %>
    </header>
    <main role="main">
       <%= render "layouts/messages" %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/nasdaq_instruments/_form.html.erb
<%= form_for(nasdaq_instrument) do |f| %>
  <% if nasdaq_instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nasdaq_instrument.errors.count, "error") %> prohibited this nasdaq_instrument from being saved:</h2>

      <ul>
      <% nasdaq_instrument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :symbol %>
    <%= f.text_field :symbol %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nasdaq_instruments/edit.html.erb
<h1>Editing Nasdaq instrument</h1>

<%= render "form", nasdaq_instrument: @nasdaq_instrument %>

<%= link_to "Show", @nasdaq_instrument %> |
<%= link_to "Back", nasdaq_instruments_path %>

app/views/nasdaq_instruments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nasdaq Instruments (<%= @nasdaq_instruments.count %>)</h1>

<div>
  <%= form_tag nasdaq_instruments_path, :method => "get" do %>
      <p>
        Name: <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", class:"btn-xs btn-primary"%>
      </p>
  <% end %>
</div>

<%= will_paginate @nasdaq_instruments %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nasdaq_instruments.each do |nasdaq_instrument| %>
      <tr>
        <td><%= link_to nasdaq_instrument.name, nasdaq_instrument %></td>
        <td><%= nasdaq_instrument.symbol %></td>
        <td><%= link_to "Destroy", nasdaq_instrument, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @nasdaq_instruments %>

<br>

<%= link_to "New Nasdaq Instrument", new_nasdaq_instrument_path %>
<p>
  <%= button_to "Load from CSV", action: "read_csv" %>
</p>

app/views/nasdaq_instruments/new.html.erb
<h1>New Nasdaq instrument</h1>

<%= render "form", nasdaq_instrument: @nasdaq_instrument %>

<%= link_to "Back", nasdaq_instruments_path %>

app/views/nasdaq_instruments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h2><%= @nasdaq_instrument.name %></h2>
</div>

<div class="row">
  <div class="col col-sm-4">
    <strong>Exchange:</strong>
    NASDAQ
    </br>
    <strong>Symbol:</strong>
    <%= @nasdaq_instrument.symbol %>
    </br>
    <strong>3 month movement:</strong>
    <% if @threemonthpr >= 0 %>
        <span style="color:green"><%= @threemonthpr %> %</span>
    <% else %>
        <span style="color:red"><%= @threemonthpr %> %</span>
    <% end %>
  </div>
  <div class="col col-sm-4">
    <strong>Close:</strong>
    <%= @fo.close %>
    </br>
    <strong>Open:</strong>
    <%= @fo.open %>
    </br>
    <strong>Market cap:</strong>
    <%= number_with_delimiter(@fo.mkt_cap, delimiter: " ") %> m
    </br>
    <strong>52 week range:</strong>
    <%= @fo.low52 %> - <%= @fo.high52 %>
    </br>
    <strong>Beta:</strong>
    <%= @fo.beta %>
    </br>
  </div>
  <div class="col col-sm-4">
    <strong>Trailing-P/E:</strong>
    <%= @fo.t_pe %>
    </br>
    <strong>Forward-P/E:</strong>
    <%= @fo.f_pe %>
    </br>
    <strong>Shares:</strong>
    <%= number_with_delimiter(@fo.shares, delimiter: " ") %> m
    </br>
    <strong>Earnings per share:</strong>
    <%= @fo.eps %> (12mth)
  </div>
</div>


<%= line_chart @weeks, title: "Historical value development", library: {backgroundColor: "#eee"} %>
<%= line_chart @threemonths, title: "3 month value development", library: {backgroundColor: "#eee"} %>

<%= link_to "Edit", edit_nasdaq_instrument_path(@nasdaq_instrument) %> |
<%= link_to "Back", nasdaq_instruments_path %>

app/views/stocks/_form.html.erb
<%= form_for(stock) do |f| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :symbol %>
    <%= f.text_field :symbol %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
  </br>
  <strong>Symbol:</strong>
  <%= @stock.symbol%>
  </br>
  <strong>3 month movement:</strong>
  <% if @threemonthpr >= 0 %>
      <span style="color:green"><%= @threemonthpr %> %</span>
  <% else %>
      <span style="color:red"><%= @threemonthpr %> %</span>
  <% end %>
</p>

<%= line_chart @weeks, title:"Historical value development", library: {backgroundColor: "#eee"} %>
<%= line_chart @threemonths, title:"3 month value development", library: {backgroundColor: "#eee"}%>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/xetra_instruments/_form.html.erb
<%= form_for(xetra_instrument) do |f| %>
  <% if xetra_instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(xetra_instrument.errors.count, "error") %> prohibited this xetra_instrument from being saved:</h2>

      <ul>
      <% xetra_instrument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :symbol %>
    <%= f.text_field :symbol %>
  </div>

  <div class="field">
    <%= f.label :isin %>
    <%= f.text_field :isin %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xetra_instruments/edit.html.erb
<h1>Editing Xetra instrument</h1>

<%= render "form", xetra_instrument: @xetra_instrument %>

<%= link_to "Show", @xetra_instrument %> |
<%= link_to "Back", xetra_instruments_path %>

app/views/xetra_instruments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Xetra Instruments (<%= @xetra_instruments.count %>)</h1>

<div>
  <%= form_tag xetra_instruments_path, :method => "get" do %>
      <p>
        Name: <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", class:"btn-xs btn-primary"%>
      </p>
  <% end %>
</div>

<%= will_paginate @xetra_instruments %>

<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @xetra_instruments.each do |xetra_instrument| %>
      <tr>
        <td><%= link_to xetra_instrument.name, xetra_instrument %></td>
        <td><%= xetra_instrument.symbol %></td>
        <td><%= link_to "Destroy", xetra_instrument, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @xetra_instruments %>

<br>

<%= link_to "New Xetra Instrument", new_xetra_instrument_path %>
<p>
  <%= button_to "Load from CSV", action: "readCsv" %>
</p>

app/views/xetra_instruments/new.html.erb
<h1>New Xetra Instrument</h1>

<%= render "form", xetra_instrument: @xetra_instrument %>

<%= link_to "Back", xetra_instruments_path %>

app/views/xetra_instruments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h2><%= @xetra_instrument.name %></h2>
</div>

<div class="row">
  <div class="col col-sm-4">
    <strong>Exchange:</strong>
    XETRA
    </br>
    <strong>Symbol:</strong>
    <%= @xetra_instrument.symbol %>
    </br>
    <strong>ISIN:</strong>
    <%= @xetra_instrument.isin %>
    </br>
  </div>
  <div class="col col-sm-4">
    <strong>Close:</strong>
    <%= @fo.close %>
    </br>
    <strong>Open:</strong>
    <%= @fo.open %>
    </br>
    <strong>Market cap:</strong>
    <%= number_with_delimiter(@fo.mkt_cap, delimiter: " ") %> m
    </br>
    <strong>52 week range:</strong>
    <%= @fo.low52 %> - <%= @fo.high52 %>
    </br>
    <strong>Beta:</strong>
    <%= @fo.beta %>
    </br>
  </div>
  <div class="col col-sm-4">
    <strong>Trailing-P/E:</strong>
    <%= @fo.t_pe %>
    </br>
    <strong>Forward-P/E:</strong>
    <%= @fo.f_pe %>
    </br>
    <strong>Shares:</strong>
    <%= number_with_delimiter(@fo.shares, delimiter: " ") %> m
    </br>
    <strong>Earnings per share:</strong>
    <%= @fo.eps %> (12mth)
  </div>
</div>

<%= link_to "Edit", edit_xetra_instrument_path(@xetra_instrument) %> |
<%= link_to "Back", xetra_instruments_path %>